migrate eventing-controller to kubebuilder3 (#12307)
* Change local dev set up

* Bump image

* Fine tune read me

* Applying PR comment

* migrate to kubebuilder 3

* create crd/external folder

* fix makefile and dockerfile

* remove unused targets

* update autogenerated

* bump image

* add default files to be disabled in kustomization

* disable kustomizing unnecessary resources

* deploy with ko

* update generated file

* bump image

* cleanup chart

* small change to help running eventing-controller locally

* reformat

* add missing +build comment

* update makefile

* update makefile and Readme

* remove outdated `deploy` target

* remove unnecessary make targets to bring the makefile more in line with
all other kyma makefiles

* rename deploy target

* bring back sample from main

* remove help target

this will be moved to another PR

* Update components/eventing-controller/README.md

Co-authored-by: Sayan Hazra <sayan.mnit@gmail.com>

* tidy go mod

* update readme for local development

Co-authored-by: Sayan Hazra <sayan.mnit@gmail.com>

diff --git a/components/eventing-controller/Makefile b/components/eventing-controller/Makefile
--- a/components/eventing-controller/Makefile
+++ b/components/eventing-controller/Makefile
@@ -1,148 +1,134 @@
 APP_NAME = eventing-controller
 APP_PATH = components/$(APP_NAME)
-BUILDPACK = eu.gcr.io/kyma-project/test-infra/buildpack-golang-kubebuilder2:v20201009-5d8104e0
+BUILDPACK = eu.gcr.io/kyma-project/test-infra/buildpack-golang-kubebuilder2:v20210601-24c60b5a
 SCRIPTS_DIR = $(realpath $(shell pwd)/../..)/common/makefiles
 
-override ENTRYPOINT = main.go
+override ENTRYPOINT = cmd/eventing-controller/main.go
 
 include $(SCRIPTS_DIR)/generic-make-go.mk
 
-# DEV image is used during development workflow only
-DEV_IMAGE = ko://github.com/kyma-project/kyma/components/eventing-controller/cmd/eventing-controller
+PROJECT_DIR := $(shell pwd)
 
-NAMESPACE = "eventing"
+NAMESPACE = "kyma-system"
 VERIFY_IGNORE := /vendor\|/mocks
 
+# Image URL to use all building/pushing image targets
+IMG ?= eventing-controller:latest
 # Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
-CRD_OPTIONS ?= "crd:crdVersions=v1"
+CRD_OPTIONS ?= "crd:trivialVersions=true,preserveUnknownFields=false"
 
 # Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
-ifneq (,$(shell which go))
 ifeq (,$(shell go env GOBIN))
 GOBIN=$(shell go env GOPATH)/bin
 else
 GOBIN=$(shell go env GOBIN)
 endif
-endif
 
-all: manager
+# Setting SHELL to bash allows bash commands to be executed by recipes.
+# This is a requirement for 'setup-envtest.sh' in the test target.
+# Options are set to exit when a recipe line exits non-zero or a piped command fails.
+SHELL = /usr/bin/env bash -o pipefail
+.SHELLFLAGS = -ec
 
-# Build controller binary
-manager: generate-local fmt-local vet-local
-	go build -o bin/controller cmd/eventing-controller/main.go
+GOBUILD_FLAGS := -v
+PKG := github.com/kyma-project/kyma/components/eventing-controller
 
-# Run against the configured Kubernetes cluster in ~/.kube/config
-# TODO Useful default values have to be found.
-run: export NATS_URL ?= nats://127.0.0.1:4222
-run: export EVENT_TYPE_PREFIX ?= sap.kyma.custom
-run: export WEBHOOK_TOKEN_ENDPOINT ?= WEBHOOK_TOKEN_ENDPOINT
-run: export DOMAIN ?= example.com
-run: generate-local fmt-local vet-local manifests
-	go run cmd/eventing-controller/main.go
 
-# Install CRDs into a cluster
-install: manifests
-	kustomize build config/crd | ko apply -f -
+help-generic:
+	@printf "\nUsage:\n  make \033[36m<target>\033[0m\n"
+	@printf "\nTargets from common makefile:\n"
 
-# Install sample CRs into a cluster
-install-samples: manifests
-	ko apply -f config/samples
 
-# Uninstall sample CRs into a cluster
-uninstall-samples: manifests
-	ko delete -f config/samples
-
-# Uninstall CRDs from a cluster
-uninstall: manifests
-	kustomize build config/crd | ko delete -f -
-
+##@ Development
 # Deploy eventing-controller in the configured Kubernetes cluster in ~/.kube/config for local development
-deploy-local: manifests deploy-local-dry-run
-	kubectl create ns ${NAMESPACE} || true
-	kustomize build config/default | ko apply -f -
+deploy: manifests-local set-up-local-env ## build the binary locally using `ko` and deploy it to a cluster
+	kustomize build config/default | envsubst | ko apply -f -
 
-# Undeploy the eventing-controller
-undeploy-local: manifests
-	kustomize build config/default | kubectl delete -f -
-
-# Dry run for deploying eventing-controller for local development
-deploy-local-dry-run: manifests
-	cd config/manager && kustomize edit set image controller=${DEV_IMAGE} && kustomize edit set namespace ${NAMESPACE}
-	cd config/rbac && kustomize edit set namespace ${NAMESPACE}
-	kustomize build config/default
-
-# Generate manifests e.g. CRD, RBAC etc.
-manifests-local: controller-gen-local
+manifests-local: controller-gen-local ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
 	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
 
-# Generate manifests e.g. CRD, RBAC etc.
-manifests:
-	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
-
-# Generate code
-generate-local: manifests-local controller-gen-local
+generate-local: controller-gen-local ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
 	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
 
-# Generate code
-generate: manifests
-	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
+set-up-local-env:
+    export NATS_URL ?= eventing-nats.kyma-system.svc.cluster.local
+    export EVENT_TYPE_PREFIX ?= sap.kyma.custom
+    export DOMAIN ?= example-domain.com
+    export WEBHOOK_TOKEN_ENDPOINT ?= "https://oauth2.${DOMAIN}/oauth2/token"
 
-verify:: mod-verify
 
-resolve-local:
-	GO111MODULE=on go mod vendor -v
+ENVTEST_ASSETS_DIR=$(PROJECT_DIR)/testbin/$(shell uname)
+test-local: test-local-nonlocal; ## Run tests.
 
-ensure-local:
-	@echo "Go modules present in component - omitting."
+setup-envtest:
+	mkdir -p ${ENVTEST_ASSETS_DIR}
+	test -f ${ENVTEST_ASSETS_DIR}/setup-envtest.sh || curl -sSLo ${ENVTEST_ASSETS_DIR}/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.8.3/hack/setup-envtest.sh
+	source ${ENVTEST_ASSETS_DIR}/setup-envtest.sh; fetch_envtest_tools $(ENVTEST_ASSETS_DIR); setup_envtest_env $(ENVTEST_ASSETS_DIR)
 
-dep-status:
-	@echo "Go modules present in component - omitting."
-
-dep-status-local:
-	@echo "Go modules present in component - omitting."
-
-mod-verify-local:
-	GO111MODULE=on go mod verify
-
-# Use it before commit
-check-code: check-imports fmt-local vet-local lint
-
-test-local: generate-local fmt-local vet-local
+test-local-nonlocal: manifests-local generate-local setup-envtest
 	go test ./... -coverprofile cover.out
 
-release: resolve generate verify build-image push-image copy-external-crds
+test-local-local: manifests-local generate-local setup-envtest
+	go test ./... -coverprofile cover.out --tags=local
+
+check-code: check-imports fmt-local vet-local lint ## Run various linters and other code checks. Use before committing
+
+run: manifests-local generate-local fmt-local vet-local set-up-local-env## Run a controller from your host. Runs with buildtags `local`
+	go run --tags=local ./cmd/eventing-controller/main.go
+
+eventing-controller: gomod-vendor-local ## Build the binary
+        @CGO_ENABLED=0 go build -o bin/$(APP_NAME) \
+        $(GOBUILD_FLAGS) \
+        $(PKG)/$(ENTRYPOINT)
+
+
+##@ Release
+
+##release: resolve-local generate-local verify-local build-image push-image copy-external-crds ## Job used by our CI to release a binary
+release:
+	$(MAKE) gomod-release-local
+
+##@ Deployment
+
+undeploy: ## Undeploy controller from the K8s cluster specified in ~/.kube/config.
+	kustomize build config/default | kubectl delete -f -
+
+CONTROLLER_GEN = $(PROJECT_DIR)/bin/$(shell uname)/controller-gen
+controller-gen-local: ## Download controller-gen locally if necessary.
+	$(call go-get-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1)
 
 path-to-referenced-charts:
-	@echo "resources/eventing-manager/eventing-controller"
+	@echo "resources/eventing"
 
-copy-crds: manifests-local
-	@echo "copying Eventing CRDs to installation/eventing"
+
+deploy-dry-run: set-up-local-env manifests-local ## Dry run for deploying eventing-controller for local development
+	cd config/rbac && kustomize edit set namespace ${NAMESPACE}
+	kustomize build config/default | envsubst
+
+##@ CRD
+
+copy-crds: manifests-local ## copy Eventing CRDs to installation/eventing
 	cp ./config/crd/bases/eventing.kyma-project.io_subscriptions.yaml ./../../installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
 	cp ./config/crd/bases/eventing.kyma-project.io_eventingbackends.yaml ./../../installation/resources/crds/eventing/eventingbackends.eventing.kyma-project.io.crd.yaml
 
-copy-external-crds:
-	@echo "copying external CRDs to config/crd/external"
+copy-external-crds: ## copy external CRDs to config/crd/external
+	mkdir -p config/crd/external
 	cp ../../installation/resources/crds/api-gateway/apirules.gateway.crd.yaml config/crd/external/apirules-gateway-kyma-project-io.yaml
+	cp ../../installation/resources/crds/application-connector/applications.applicationconnector.crd.yaml config/crd/external/applications-applicationconnector-kyma-project-io.yaml
 
-# find or download controller-gen
-# download controller-gen if necessary
-.PHONY: controller-gen-local
-controller-gen-local:
-ifeq (, $(shell which controller-gen))
-	@{ \
-	set -e ;\
-	CONTROLLER_GEN_TMP_DIR=$$(mktemp -d) ;\
-	cd $$CONTROLLER_GEN_TMP_DIR ;\
-	if [ ! $(which go) ]; then \
-		go mod init tmp ; \
-		go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.6.0 ; \
-		rm -rf $$CONTROLLER_GEN_TMP_DIR ; \
-	fi; \
-	}
-CONTROLLER_GEN=$(GOBIN)/controller-gen
-else
-CONTROLLER_GEN=$(shell which controller-gen)
-endif
+# go-get-tool will 'go get' any package $2 and install it to $1.
+ARCH := $(shell uname)
+define go-get-tool
+@[ -f $(1) ] || { \
+set -e ;\
+TMP_DIR=$$(mktemp -d) ;\
+cd $$TMP_DIR ;\
+go mod init tmp ;\
+echo "Downloading $(2)" ;\
+GOBIN=$(PROJECT_DIR)/bin/$(ARCH) go get $(2) ;\
+rm -rf $$TMP_DIR ;\
+}
+endef
 
 $(eval $(call buildpack-cp-ro,resolve))
 $(eval $(call buildpack-mount,mod-verify))
@@ -151,58 +137,8 @@ $(eval $(call buildpack-mount,controller-gen))
 $(eval $(call buildpack-mount,generate))
 $(eval $(call buildpack-mount,manifests))
 
-# produce goals for each cmd program ("bin1 bin2 ...")
-cmds := $(foreach dir,$(wildcard cmd/*),$(notdir $(dir)))
-# produce goals to build images for each cmd program ("bin1.image bin2.image ...")
-cmds_images = $(foreach cmd,$(cmds),$(cmd).image)
-cmds_clean = $(foreach cmd,$(cmds),$(cmd).clean)
-# produce goals to push images for each cmd program ("bin1.image.push bin2.image.push ...")
-cmds_images_push = $(foreach img,$(cmds_images),$(img).push)
-
-MOUNT_TARGETS = $(cmds)
-$(foreach t,$(MOUNT_TARGETS),$(eval $(call buildpack-mount,$(t))))
-
-.PHONY: clean
-clean: $(cmds_clean) resolve_clean licenses_clean
-
-$(cmds_clean): %.clean:
-	rm -f $*
-
 resolve_clean:
 	rm -rf vendor
 
 licenses_clean:
 	rm -rf licenses
-
-build-local: $(cmds) test-local ;
-
-.PHONY: $(cmds_images) $(cmds_images_push)
-
-# override image goals from common Makefile because we need to build several images
-build-image: $(cmds_images) ;
-push-image: $(cmds_images_push) ;
-
-# Example:
-#   make eventing-controller
-GOBUILD_FLAGS := -v
-PKG := github.com/kyma-project/kyma/components/eventing-controller
-$(cmds): %: resolve-local
-	@echo "+ Building $*"
-	@CGO_ENABLED=0 go build -o $* \
-		$(GOBUILD_FLAGS) \
-		$(PKG)/cmd/$*
-
-# Example:
-#   make eventing-controller.image
-$(cmds_images): %.image: build pull-licenses
-	$(eval $@_img_name := $*)
-	@echo "+ Building container image $($@_img_name)"
-	docker image build -f cmd/$*/Dockerfile -t $($@_img_name) .
-
-# Example:
-#   make eventing-controller.image.push
-$(cmds_images_push): %.push: %
-	$(eval $@_img_name := $(subst .image,,$*))
-	@echo "+ Pushing container image $($@_img_name)"
-	docker image tag $($@_img_name) $(DOCKER_PUSH_REPOSITORY)$(DOCKER_PUSH_DIRECTORY)/$($@_img_name):$(TAG)
-	docker image push $(DOCKER_PUSH_REPOSITORY)$(DOCKER_PUSH_DIRECTORY)/$($@_img_name):$(TAG)
