Make 2to3 more resilient

diff --git a/installation/resources/installer-local.yaml b/installation/resources/installer-local.yaml
--- a/installation/resources/installer-local.yaml
+++ b/installation/resources/installer-local.yaml
@@ -221,12 +221,17 @@ spec:
           ${HELM_2_BINARY} init -c
 
           if [[ $(kubectl get -n kube-system deploy tiller-deploy -o name) ]]; then
-            kubectl get -n "${NAMESPACE}" secret "${SECRET_NAME}" -o jsonpath="{.data['global\\.helm\\.ca\\.crt']}" | base64 --decode > "$(helm home)/ca.pem"
-            kubectl get -n "${NAMESPACE}" secret "${SECRET_NAME}" -o jsonpath="{.data['global\\.helm\\.tls\\.crt']}" | base64 --decode > "$(helm home)/cert.pem"
-            kubectl get -n "${NAMESPACE}" secret "${SECRET_NAME}" -o jsonpath="{.data['global\\.helm\\.tls\\.key']}" | base64 --decode > "$(helm home)/key.pem"
+            if [[ $(kubectl get -n "${NAMESPACE}" secret "${SECRET_NAME}" -o name) ]]; then
+              kubectl get -n "${NAMESPACE}" secret "${SECRET_NAME}" -o jsonpath="{.data['global\\.helm\\.ca\\.crt']}" | base64 --decode > "$(helm home)/ca.pem"
+              kubectl get -n "${NAMESPACE}" secret "${SECRET_NAME}" -o jsonpath="{.data['global\\.helm\\.tls\\.crt']}" | base64 --decode > "$(helm home)/cert.pem"
+              kubectl get -n "${NAMESPACE}" secret "${SECRET_NAME}" -o jsonpath="{.data['global\\.helm\\.tls\\.key']}" | base64 --decode > "$(helm home)/key.pem"
+            else
+              echo "------> No HELM_2 Certs found, failing"
+              exit 1
+            fi
           else
-            echo "------> No HELM_2 certs found, exiting"
-            exit 1
+            echo "------> No Tiller deployment found, exiting gracefully"
+            exit 0
           fi
 
           echo "---> Get current releases"
