Update go vet

diff --git a/.github/workflows/post-master-binding-k3s.yml b/.github/workflows/post-master-binding-k3s.yml
--- a/.github/workflows/post-master-binding-k3s.yml
+++ b/.github/workflows/post-master-binding-k3s.yml
@@ -2,7 +2,7 @@ name: Binding-post-master
 on: 
   push:
     branches:
-      - main
+      - master
   
 defaults:
   run:
@@ -30,8 +30,11 @@ jobs:
             echo "Some files are not properly formatted"
             exit 1
           fi
-          go vet ./...
-
+          goVetResult=$(go vet ./...)
+          if [ $(echo ${#goVetResult}) != 0 ]; then
+          echo -e "go vet errors \n$goVetResult"
+          exit 1
+          fi
 
       - name: Setup gcloud
         uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
diff --git a/.github/workflows/pre-master-binding-k3s.yml b/.github/workflows/pre-master-binding-k3s.yml
--- a/.github/workflows/pre-master-binding-k3s.yml
+++ b/.github/workflows/pre-master-binding-k3s.yml
@@ -35,8 +35,11 @@ jobs:
           echo "Some files are not properly formatted"
           exit 1
         fi
-        go vet ./...
-
+        goVetResult=$(go vet ./...)
+        if [ $(echo ${#goVetResult}) != 0 ]; then
+            echo -e "go vet errors \n$goVetResult"
+            exit 1
+        fi
 
     - name: Setup gcloud
       uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
@@ -100,19 +103,3 @@ jobs:
             conclusion: process.env.conclusion
           });
           return result;
-
-
-  binding-pre-master:
-    env:
-      PR_NUMBER: ${{ github.event.number }}
-      PROJECT_ID: "sap-se-cx-gopher"
-    runs-on: ubuntu-latest
-    timeout-minutes: 15
-    steps:
-      - name: Set up Go 1.14
-        uses: actions/setup-go@v2
-        with:
-          go-version: ^1.14
-
-      - uses: actions/checkout@v2
-
